### ISSUE TITLE
Downsampling in calibration and discovery QQ plots

### ISSUE THREAD

**Issue by jdeu1023** [Katsevich-Lab/sceptre#50]

**Comment by timothy-barry** [comment]
Note that in some cases the number of discovery pairs may not match the number of negative control pairs (i.e., there may be more discovery than negative control pairs). In this case we should downsample the discovery pairs so that the number of pairs across the two groups coincides, while printing a warning message.

**Comment by timothy-barry** [comment]
EDIT: In the event that there are fewer negative control pairs than discovery pairs, it probably makes most sense to simply not superimpose the negative control pairs on top of the discovery pairs in the discovery plot.
